### PR TITLE
keymaster: fix potential size length mismatch between ta and pta when do msg serilization

### PR DESCRIPTION
**Pull request by andyzsh68**
Signed-off-by: Andy Zhang <andyzsh68@google.com>

### CODE REVIEW

**Comment by andyzsh68** [comment]
@omasse06 @vchong 
please also sync optee-os code on branch [kmgk_pta_3.3.0_serialization](https://github.com/andyzsh68/optee_os/tree/kmgk_pta_3.3.0_serialization).
thanks.

On my side, I used latest kmgk code with oliver's attestation extention [patch](https://github.com/andyzsh68/optee_os/commit/7936d32692f18a2265c64615c3af6979065cd2a4) , without this patch, got one test case failed as following:
[----------] Global test environment tear-down
[==========] 108 tests from 12 test cases ran. (348278 ms total)
[  PASSED  ] 107 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AttestationTest.EcAttestation

 1 FAILED TEST

with this patch, got the same failed case. So please confirm on your side.
thanks.

**Comment by vchong** [comment]
@andyzsh68 There are still calls to `TA_deserialize_blob()` in `attestation.c`. Should I just replace those too?

**Comment by andyzsh68** [comment]
it depends on how the host side serialize the message. but i have not found how the host call the two commands controlled by the macro CFG_ATTESTATION_PROVISIONING(i do the test without eanabling  the macro).
can you share some info about the commands?


thanks.

**Comment by omasse-nxp** [comment]
Your test should be done without enabling CFG_ATTESTATION_PROVISIONING macro. Otherwise you should use KM_SET_ATTESTATION_KEY and KM_APPEND_ATTESTATION_CERT_CHAIN to add keys and certificate to enable attestation.
The command currently use serialization with 64bits encoded size (not akms one).

**Comment by vchong** [comment]
@andyzsh68 @omasse06 I'm a bit confused here.

> Your test should be done without enabling CFG_ATTESTATION_PROVISIONING macro.

@omasse06 I guess it would be wider coverage for us to test with this disabled and for you to test with this enabled, but don't you want us to test with this enabled too? Also, if you don't test with this disabled as well (I assume you don't), then it might be possible too for some tests to fail due to some untested code path, like the ones Andy mentioned above?

> Otherwise you should use KM_SET_ATTESTATION_KEY and KM_APPEND_ATTESTATION_CERT_CHAIN to add keys and certificate to enable attestation.

I couldn't find anywhere in both VTS and CTS (and even vold) where these commands are called. Do you know how these can be tested?

> The command currently use serialization with 64bits encoded size (not akms one).

@andyzsh68 I see you've changed to PR to totally replace the remaining 2 `TA_deserialize_blob()` in `attestation.c`, but won't that just create a mismatch again with what Olivier said above?

@omasse06 where is this serialization done? Can't we replace just replace it with 32bits encoded size (akms one)?

**Comment by andyzsh68** [comment]
@vchong
In fact, I removed function TA_deserialize_blob at ta side. It is better to unify the blob serialization functions whatever between ca and ta or between ta and pta, or it is too complicated for the serilization and the debugging(dump hex and comparing the hex according to the serialzation code).



andyzsh68@gmail.com

**Comment by omasse-nxp** [comment]
@vchong  you are right, I have to test without attestation provisioning too. If you want to test the CFG_ATTESTATION_PROVISIONING, you will need rsa an ecdsa private keys and certificate chain signing with that keys.
I'm in vacation until august 12 without access to our repo. As Andy just done it will be easier to use the same serialization/de-serialization for all component. I will update my code accordingly as soon as I come back from holidays.

**Comment by vchong** [comment]
@andyzsh68 @omasse06 Yes, I guess we're all in agreement that it's obviously better to use just one de(serialization) function.

@omasse06 I suppose I can generate some kind of key and cert chain using openssl or similar tools? Then would you be able to share your code for calling and testing KM_SET_ATTESTATION_KEY and KM_APPEND_ATTESTATION_CERT_CHAIN? Or do I need something signed by Google in order for the chain to be valid? Anyway, have a great vacation and tty when you get back. I'll test without CFG_ATTESTATION_PROVISIONING in the meantime.

**Comment by msopiha-linaro** [comment]
@andyzsh68 @omasse06 
Can you please confirm that TEE_GetSystemTime() on your platform returns nonzero result?

**Comment by vchong** [comment]
Google test keys and certs are for partners only and no specific public doc available atm for generating them but testing without CFG_ATTESTATION_PROVISIONING is ok and testing within NXP internally with CFG_ATTESTATION_PROVISIONING is also ok so merging.

**Comment by vchong** [comment]
Merged. @andyzsh68 Thanks again for the contribution and help with debugging + testing!

**Pull request merged**
