### PR TITLE
km3: using android serializing keymaster message functions

### PR DESCRIPTION
**Pull request by andyzsh68**
1. km3 directory structure and most of the hidl code are from android trusty.
2. tested by VtsHalKeymasterV3_0TargetTest, and all test cases are passed.
[==========] 108 tests from 12 test cases ran. (4018798 ms total)
[  PASSED  ] 108 tests.

### CODE REVIEW

**Comment by vchong** [comment]
Thanks a lot Andy! Appreciate your contribution. Will try to review this asap.

**Comment by vchong** [comment]
@andyzsh68 

So very sorry for the delay! Had to put out many fires in succession and just finally got to integrating and testing this. I merged this manually with minor and cosmetic modifications, partly due to the number of patches we've added to master during these times.

Thank you very much for your contribution! Awesome work you did here not just with the serializing functions but also 'syncing' the source tree to mirror that of trusty. It'll make referencing and adding future versions easier. That said, if you have any KM4 updates that you'd be willing to share, we'd welcome PRs for them as well! ;)

Also, I previously had a fork of your `kmgk_3.3.0_km2` repo, but it got deleted automatically because you either deleted your repo or removed the list of collaborators from your repo. Do you mind sharing it again please? It'd be something good to have as a reference.

Thanks!

**Comment by vchong** [comment]
Merged manually

**Comment by gchww** [comment]
@vchong 
It is good to hear the progress. Glad to do some work for the project.
added you to kmgk_3.3.0_km2 repo, please check.

Thanks!

**Pull request closed without merging**
